-- Migration 018: ALT-2022 follow-ups (ALT-2027)
--
-- Three security/perf hardening passes on the migration 017 schema:
--
--   1. Split free-form `actor` into `actor_user_id` + `actor_agent_id` so a
--      workspace-scoped caller can no longer spoof another principal's identity
--      in the audit ledger. The repository derives both values from server-held
--      session context, never from caller-supplied strings.
--
--   2. Expand the action enum to allow `read_failed` (decrypt/auth-tag failure
--      observability) and `list` (single audit row per listSecretSummaries call,
--      so SIEM sees enumeration without exploding the ledger).
--
--   3. Add `value_mask_suffix` to provisioned_company_secrets so the list path
--      no longer needs to decrypt every row to compute a masked tail. The
--      suffix is a non-sensitive last-4 of the plaintext, written at encrypt
--      time alongside the ciphertext.

BEGIN;

-- ============================================================
-- 1. Split actor into actor_user_id + actor_agent_id
-- ============================================================

ALTER TABLE control_plane_secret_audit
  ADD COLUMN IF NOT EXISTS actor_user_id text NULL,
  ADD COLUMN IF NOT EXISTS actor_agent_id text NULL;

-- Best-effort backfill for any pre-existing rows (legacy free-form actor).
-- We cannot retroactively know whether the legacy string was a user or agent
-- id, so we treat it as a user id - the column is NULL-safe either way. Wrap
-- the backfill so re-running this migration after the column is dropped is a
-- no-op (sqlMigrations.ts re-applies every file on startup).
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
     WHERE table_name = 'control_plane_secret_audit'
       AND column_name = 'actor'
  ) THEN
    EXECUTE $sql$
      UPDATE control_plane_secret_audit
         SET actor_user_id = actor
       WHERE actor IS NOT NULL
         AND actor_user_id IS NULL
         AND actor_agent_id IS NULL
    $sql$;
  END IF;
END$$;

ALTER TABLE control_plane_secret_audit DROP COLUMN IF EXISTS actor;

-- At least one of the actor fields must be present so audit rows always
-- attribute to a principal that the server can vouch for.
ALTER TABLE control_plane_secret_audit
  DROP CONSTRAINT IF EXISTS control_plane_secret_audit_actor_present;
ALTER TABLE control_plane_secret_audit
  ADD CONSTRAINT control_plane_secret_audit_actor_present
  CHECK (actor_user_id IS NOT NULL OR actor_agent_id IS NOT NULL);

CREATE INDEX IF NOT EXISTS idx_control_plane_secret_audit_actor_user
  ON control_plane_secret_audit (actor_user_id)
  WHERE actor_user_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_control_plane_secret_audit_actor_agent
  ON control_plane_secret_audit (actor_agent_id)
  WHERE actor_agent_id IS NOT NULL;

-- ============================================================
-- 2. Expand action enum: add read_failed + list
-- ============================================================
--
-- The original CHECK constraint was created inline in migration 017, so its
-- name is auto-generated by Postgres. Resolve it dynamically and replace.

DO $$
DECLARE
  legacy_constraint text;
BEGIN
  SELECT conname INTO legacy_constraint
    FROM pg_constraint
   WHERE conrelid = 'control_plane_secret_audit'::regclass
     AND contype = 'c'
     AND pg_get_constraintdef(oid) ILIKE '%action%IN%'
   LIMIT 1;
  IF legacy_constraint IS NOT NULL THEN
    EXECUTE format(
      'ALTER TABLE control_plane_secret_audit DROP CONSTRAINT %I',
      legacy_constraint
    );
  END IF;
END$$;

ALTER TABLE control_plane_secret_audit
  DROP CONSTRAINT IF EXISTS control_plane_secret_audit_action_check;
ALTER TABLE control_plane_secret_audit
  ADD CONSTRAINT control_plane_secret_audit_action_check
  CHECK (action IN ('read', 'read_failed', 'write', 'rotate', 'delete', 'list'));

-- ============================================================
-- 3. Harden append-only enforcement: rebuild the no-UPDATE / no-DELETE
--    policies as RESTRICTIVE so they cannot be bypassed by the permissive
--    tenant_isolation policy. Permissive policies OR together, so the
--    original migration 017 statements left UPDATE/DELETE allowed inside
--    the owning workspace. Restrictive policies AND together, which is
--    what append-only requires.
-- ============================================================

DROP POLICY IF EXISTS control_plane_secret_audit_no_update
  ON control_plane_secret_audit;
DROP POLICY IF EXISTS control_plane_secret_audit_no_delete
  ON control_plane_secret_audit;

CREATE POLICY control_plane_secret_audit_no_update
  ON control_plane_secret_audit
  AS RESTRICTIVE
  FOR UPDATE
  USING (false)
  WITH CHECK (false);

CREATE POLICY control_plane_secret_audit_no_delete
  ON control_plane_secret_audit
  AS RESTRICTIVE
  FOR DELETE
  USING (false);

-- ============================================================
-- 4. value_mask_suffix on provisioned_company_secrets
-- ============================================================
--
-- Non-sensitive last-4 of the plaintext, written at encrypt time. Lets the
-- list path skip decryption entirely and avoids pulling every row's plaintext
-- into process memory just to compute a UI mask.
--
-- Length is bounded so a future bug cannot stash a full secret here.

ALTER TABLE provisioned_company_secrets
  ADD COLUMN IF NOT EXISTS value_mask_suffix text NULL;

ALTER TABLE provisioned_company_secrets
  DROP CONSTRAINT IF EXISTS provisioned_company_secrets_mask_suffix_length;
ALTER TABLE provisioned_company_secrets
  ADD CONSTRAINT provisioned_company_secrets_mask_suffix_length
  CHECK (value_mask_suffix IS NULL OR char_length(value_mask_suffix) <= 4);

COMMIT;
