apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: autoflow-ingress
  namespace: autoflow-staging
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - staging.helloautoflow.com
      secretName: autoflow-staging-tls
  rules:
    - host: staging.helloautoflow.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
