apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: autoflow-production-api
  namespace: autoflow-production
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.helloautoflow.com
      secretName: autoflow-production-api-tls
  rules:
    - host: api.helloautoflow.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80
