import { z } from "zod";

export const TEAM_ASSEMBLY_SCHEMA_VERSION = "2026-04-27";

const modelTierSchema = z.enum(["lite", "standard", "power"]);

export const normalizedGoalDocumentSchema = z.object({
  sourceType: z.enum(["free_text", "notion", "google-doc", "markdown"]),
  goal: z.string().trim().min(1),
  targetCustomer: z.string().trim().nullable(),
  successMetrics: z.array(z.string().trim().min(1)),
  constraints: z.array(z.string().trim().min(1)),
  budget: z.string().trim().nullable(),
  timeHorizon: z.string().trim().nullable(),
  importedContextSummary: z.string().trim().nullable().optional(),
  planReadinessThreshold: z.number().min(0).max(1),
});

export const prdSchema = z.object({
  title: z.string().trim().min(1),
  summary: z.string().trim().min(1),
  targetCustomer: z.string().trim().min(1),
  problemStatement: z.string().trim().min(1),
  proposedSolution: z.string().trim().min(1),
  successMetrics: z.array(z.string().trim().min(1)).min(1),
  constraints: z.array(z.string().trim().min(1)).min(1),
  budget: z.string().trim().min(1),
  timeHorizon: z.string().trim().min(1),
  assumptions: z.array(z.string().trim().min(1)).default([]),
  risks: z.array(z.string().trim().min(1)).default([]),
  openQuestions: z.array(z.string().trim().min(1)).default([]),
});

const roleLibraryEntrySchema = z.object({
  roleKey: z.string().trim().min(1),
  title: z.string().trim().min(1),
  roleType: z.enum(["executive", "operator"]),
  department: z.string().trim().min(1),
  mandate: z.string().trim().min(1),
  defaultReportsToRoleKey: z.string().trim().min(1).nullable().optional(),
  defaultSkills: z.array(z.string().trim().min(1)).default([]),
  defaultTools: z.array(z.string().trim().min(1)).default([]),
  defaultModelTier: modelTierSchema,
  hiringSignals: z.array(z.string().trim().min(1)).default([]),
});

const staffingRecommendationSchema = z.object({
  roleKey: z.string().trim().min(1),
  title: z.string().trim().min(1),
  roleType: z.enum(["executive", "operator"]),
  department: z.string().trim().min(1),
  headcount: z.number().int().positive(),
  reportsToRoleKey: z.string().trim().min(1).nullable(),
  mandate: z.string().trim().min(1),
  justification: z.string().trim().min(1),
  kpis: z.array(z.string().trim().min(1)).min(1),
  skills: z.array(z.string().trim().min(1)).min(1),
  tools: z.array(z.string().trim().min(1)).min(1),
  modelTier: modelTierSchema,
  budgetMonthlyUsd: z.number().min(0).nullable(),
  provisioningInstructions: z.string().trim().min(1),
});

const phasePlanSchema = z.object({
  objectives: z.array(z.string().trim().min(1)).min(1),
  deliverables: z.array(z.string().trim().min(1)).min(1),
  ownerRoleKeys: z.array(z.string().trim().min(1)).min(1),
});

const teamAssemblyResultSchema = z.object({
  schemaVersion: z.literal(TEAM_ASSEMBLY_SCHEMA_VERSION),
  company: z.object({
    name: z.string().trim().min(1).nullable(),
    goal: z.string().trim().min(1),
    targetCustomer: z.string().trim().min(1).nullable(),
    budget: z.string().trim().min(1).nullable(),
    timeHorizon: z.string().trim().min(1).nullable(),
  }),
  summary: z.string().trim().min(1),
  rationale: z.string().trim().min(1),
  orgChart: z.object({
    executives: z.array(staffingRecommendationSchema),
    operators: z.array(staffingRecommendationSchema),
    reportingLines: z.array(
      z.object({
        managerRoleKey: z.string().trim().min(1),
        reportRoleKey: z.string().trim().min(1),
      })
    ),
  }),
  provisioningPlan: z.object({
    teamName: z.string().trim().min(1),
    deploymentMode: z.literal("continuous_agents"),
    agents: z.array(staffingRecommendationSchema).min(1),
  }),
  roadmap306090: z.object({
    day30: phasePlanSchema,
    day60: phasePlanSchema,
    day90: phasePlanSchema,
  }),
});

export const DEFAULT_ROLE_LIBRARY = [
  {
    roleKey: "ceo",
    title: "CEO",
    roleType: "executive",
    department: "executive",
    mandate: "Own strategy, resource allocation, and cross-functional prioritization.",
    defaultReportsToRoleKey: null,
    defaultSkills: ["paperclip"],
    defaultTools: ["notion", "slack", "github"],
    defaultModelTier: "power",
    hiringSignals: ["ambiguous business strategy", "multi-function coordination", "budget tradeoffs"],
  },
  {
    roleKey: "cto",
    title: "CTO",
    roleType: "executive",
    department: "engineering",
    mandate: "Own product architecture, engineering throughput, and technical risk management.",
    defaultReportsToRoleKey: "ceo",
    defaultSkills: ["paperclip", "cto-routines"],
    defaultTools: ["github", "vercel"],
    defaultModelTier: "power",
    hiringSignals: ["software product delivery", "integration complexity", "technical roadmap"],
  },
  {
    roleKey: "cmo",
    title: "CMO",
    roleType: "executive",
    department: "marketing",
    mandate: "Own positioning, demand generation, and content strategy.",
    defaultReportsToRoleKey: "ceo",
    defaultSkills: ["paperclip", "cmo-routines"],
    defaultTools: ["notion", "slack"],
    defaultModelTier: "power",
    hiringSignals: ["audience acquisition", "content moat", "brand building"],
  },
  {
    roleKey: "cro",
    title: "CRO",
    roleType: "executive",
    department: "sales",
    mandate: "Own pipeline creation, conversion, and revenue expansion.",
    defaultReportsToRoleKey: "ceo",
    defaultSkills: ["paperclip", "cro-routines"],
    defaultTools: ["attio", "gmail", "slack"],
    defaultModelTier: "power",
    hiringSignals: ["outbound sales", "design partners", "revenue targets"],
  },
  {
    roleKey: "cfo",
    title: "CFO",
    roleType: "executive",
    department: "finance",
    mandate: "Own budget control, cash planning, and financial reporting.",
    defaultReportsToRoleKey: "ceo",
    defaultSkills: ["paperclip"],
    defaultTools: ["stripe", "notion"],
    defaultModelTier: "standard",
    hiringSignals: ["tight budgets", "financial controls", "unit economics"],
  },
  {
    roleKey: "ciso",
    title: "CISO",
    roleType: "executive",
    department: "security",
    mandate: "Own security posture, data handling, and compliance controls.",
    defaultReportsToRoleKey: "ceo",
    defaultSkills: ["paperclip", "security-review"],
    defaultTools: ["github", "notion"],
    defaultModelTier: "standard",
    hiringSignals: ["regulated data", "security-sensitive workflows", "customer trust requirements"],
  },
  {
    roleKey: "backend-engineer",
    title: "Backend Engineer",
    roleType: "operator",
    department: "engineering",
    mandate: "Build APIs, business logic, and data integrations.",
    defaultReportsToRoleKey: "cto",
    defaultSkills: ["paperclip", "nodejs-backend-patterns"],
    defaultTools: ["github", "vercel"],
    defaultModelTier: "standard",
    hiringSignals: ["API delivery", "data pipelines", "integration work"],
  },
  {
    roleKey: "frontend-engineer",
    title: "Frontend Engineer",
    roleType: "operator",
    department: "engineering",
    mandate: "Deliver user-facing web experiences and review flows.",
    defaultReportsToRoleKey: "cto",
    defaultSkills: ["paperclip", "frontend-design"],
    defaultTools: ["github", "vercel"],
    defaultModelTier: "standard",
    hiringSignals: ["dashboard work", "review UI", "user-facing product"],
  },
  {
    roleKey: "qa-engineer",
    title: "QA Engineer",
    roleType: "operator",
    department: "engineering",
    mandate: "Verify product quality through regression and release checks.",
    defaultReportsToRoleKey: "cto",
    defaultSkills: ["paperclip", "javascript-testing-patterns"],
    defaultTools: ["github"],
    defaultModelTier: "lite",
    hiringSignals: ["quality gates", "release risk", "regression coverage"],
  },
  {
    roleKey: "devops-engineer",
    title: "DevOps Engineer",
    roleType: "operator",
    department: "engineering",
    mandate: "Own deployment pipelines and runtime reliability.",
    defaultReportsToRoleKey: "cto",
    defaultSkills: ["paperclip", "devops-rollout-plan"],
    defaultTools: ["github", "vercel"],
    defaultModelTier: "standard",
    hiringSignals: ["serving infrastructure", "runtime operations", "ci/cd"],
  },
  {
    roleKey: "product-designer",
    title: "Product Designer",
    roleType: "operator",
    department: "design",
    mandate: "Translate product strategy into user flows and interfaces.",
    defaultReportsToRoleKey: "cto",
    defaultSkills: ["paperclip", "ui-ux-pro-max"],
    defaultTools: ["figma", "notion"],
    defaultModelTier: "standard",
    hiringSignals: ["new product UX", "review workflows", "complex user journeys"],
  },
  {
    roleKey: "content-lead",
    title: "Content Lead",
    roleType: "operator",
    department: "marketing",
    mandate: "Operate the editorial pipeline and publishable asset creation.",
    defaultReportsToRoleKey: "cmo",
    defaultSkills: ["paperclip", "content-lead-routines"],
    defaultTools: ["notion", "slack"],
    defaultModelTier: "standard",
    hiringSignals: ["content engine", "SEO program", "editorial calendar"],
  },
  {
    roleKey: "seo-specialist",
    title: "SEO Specialist",
    roleType: "operator",
    department: "marketing",
    mandate: "Grow qualified traffic through search demand capture.",
    defaultReportsToRoleKey: "cmo",
    defaultSkills: ["paperclip"],
    defaultTools: ["google-drive", "notion"],
    defaultModelTier: "lite",
    hiringSignals: ["organic acquisition", "content discovery", "search demand"],
  },
  {
    roleKey: "sdr",
    title: "SDR",
    roleType: "operator",
    department: "sales",
    mandate: "Generate pipeline through outbound prospecting and qualification.",
    defaultReportsToRoleKey: "cro",
    defaultSkills: ["paperclip"],
    defaultTools: ["attio", "gmail", "slack"],
    defaultModelTier: "lite",
    hiringSignals: ["outbound motion", "pilot recruitment", "top-of-funnel targets"],
  },
  {
    roleKey: "account-executive",
    title: "Account Executive",
    roleType: "operator",
    department: "sales",
    mandate: "Own discovery, proposal, and close workflows.",
    defaultReportsToRoleKey: "cro",
    defaultSkills: ["paperclip"],
    defaultTools: ["attio", "gmail"],
    defaultModelTier: "standard",
    hiringSignals: ["high-ticket sales", "pipeline conversion", "pilot closes"],
  },
  {
    roleKey: "bookkeeper",
    title: "Bookkeeper",
    roleType: "operator",
    department: "finance",
    mandate: "Maintain transaction hygiene and reporting cadence.",
    defaultReportsToRoleKey: "cfo",
    defaultSkills: ["paperclip"],
    defaultTools: ["stripe", "notion"],
    defaultModelTier: "lite",
    hiringSignals: ["transaction-heavy business", "financial reporting", "expense controls"],
  },
  {
    roleKey: "security-engineer",
    title: "Security Engineer",
    roleType: "operator",
    department: "security",
    mandate: "Implement secure defaults and controls for sensitive systems.",
    defaultReportsToRoleKey: "ciso",
    defaultSkills: ["paperclip", "security-review"],
    defaultTools: ["github", "notion"],
    defaultModelTier: "standard",
    hiringSignals: ["customer data", "auth systems", "compliance controls"],
  },
] as const satisfies readonly z.input<typeof roleLibraryEntrySchema>[];

export const teamAssemblyRequestSchema = z.object({
  companyName: z.string().trim().min(1).optional(),
  normalizedGoalDocument: normalizedGoalDocumentSchema,
  prd: prdSchema.optional(),
  roleLibrary: z.array(roleLibraryEntrySchema).optional().default([...DEFAULT_ROLE_LIBRARY]),
});

export type TeamAssemblyRequest = z.infer<typeof teamAssemblyRequestSchema>;
export type TeamAssemblyResult = z.infer<typeof teamAssemblyResultSchema>;

export function buildTeamAssemblyPrompt(input: TeamAssemblyRequest): string {
  const companyName = input.companyName?.trim() || "Unnamed Company";

  return [
    "You are the CEO agent for AutoFlow.",
    "Turn a normalized goal document into a staffing plan drawn from the provided role library.",
    "Return JSON only. Do not wrap the response in markdown fences.",
    `Use schemaVersion exactly \"${TEAM_ASSEMBLY_SCHEMA_VERSION}\".`,
    "Select only the roles needed to achieve the goal in the next 90 days.",
    "Prefer lean teams and do not invent roles outside the provided role library.",
    "Every recommended role must include KPIs, skills, tools, model tier, and provisioning instructions.",
    "Use budgetMonthlyUsd as null if you cannot infer a credible number from the context.",
    "The provisioningPlan.agents array must contain every recommended role exactly once.",
    "Make reportingLines consistent with reportsToRoleKey values.",
    "",
    "Return this JSON object shape:",
    "{",
    `  "schemaVersion": "${TEAM_ASSEMBLY_SCHEMA_VERSION}",`,
    '  "company": { "name": string | null, "goal": string, "targetCustomer": string | null, "budget": string | null, "timeHorizon": string | null },',
    '  "summary": string,',
    '  "rationale": string,',
    '  "orgChart": {',
    '    "executives": [StaffingRecommendation],',
    '    "operators": [StaffingRecommendation],',
    '    "reportingLines": [{ "managerRoleKey": string, "reportRoleKey": string }]',
    "  },",
    '  "provisioningPlan": {',
    '    "teamName": string,',
    '    "deploymentMode": "continuous_agents",',
    '    "agents": [StaffingRecommendation]',
    "  },",
    '  "roadmap306090": {',
    '    "day30": { "objectives": string[], "deliverables": string[], "ownerRoleKeys": string[] },',
    '    "day60": { "objectives": string[], "deliverables": string[], "ownerRoleKeys": string[] },',
    '    "day90": { "objectives": string[], "deliverables": string[], "ownerRoleKeys": string[] }',
    "  }",
    "}",
    "",
    "StaffingRecommendation shape:",
    "{",
    '  "roleKey": string,',
    '  "title": string,',
    '  "roleType": "executive" | "operator",',
    '  "department": string,',
    '  "headcount": number,',
    '  "reportsToRoleKey": string | null,',
    '  "mandate": string,',
    '  "justification": string,',
    '  "kpis": string[],',
    '  "skills": string[],',
    '  "tools": string[],',
    '  "modelTier": "lite" | "standard" | "power",',
    '  "budgetMonthlyUsd": number | null,',
    '  "provisioningInstructions": string',
    "}",
    "",
    `Company name: ${companyName}`,
    "",
    `Normalized goal document:\n${JSON.stringify(input.normalizedGoalDocument, null, 2)}`,
    "",
    `PRD:\n${JSON.stringify(input.prd ?? null, null, 2)}`,
    "",
    `Role library:\n${JSON.stringify(input.roleLibrary, null, 2)}`,
  ].join("\n");
}

export function parseTeamAssemblyResponse(rawText: string): TeamAssemblyResult {
  const cleaned = rawText.replace(/^```(?:json)?\s*/i, "").replace(/\s*```$/, "").trim();
  return teamAssemblyResultSchema.parse(JSON.parse(cleaned) as unknown);
}
